### ISSUE TITLE
The given key 'Status' was not present in the dictionary

### ISSUE THREAD

**Issue by baur** [Manjey73/OpenDrivers#1]
2024-06-17 16:48:34 Ошибка при вызове метода Session устройства [16] РП15 Ввод-1 Яч.#2:
System.Collections.Generic.KeyNotFoundException: The given key 'Status' was not present in the dictionary.
   at Scada.Comm.Drivers.DrvMercury23x.Logic.DevMercury23xLogic.Session()
   at Scada.Comm.Engine.DeviceWrapper.Session()

[line001.log](https://github.com/user-attachments/files/15866666/line001.log)

**Comment by baur** [comment]
Все счетчики использует один и тот же конфиг:  
[Mercury230energy.xml.txt](https://github.com/user-attachments/files/15869548/Mercury230energy.xml.txt)

**Comment by baur** [comment]
[line001.log](https://github.com/user-attachments/files/15871029/line001.log)

**Comment by baur** [comment]
Проверил доступные на данный момент, единственный со статусом **норма** оказался другой модели ART-00 PQSIDN остальные ART-00 N

![image](https://github.com/Manjey73/OpenDrivers/assets/2898361/1385d007-7036-4a84-b10f-31cad85741b2)


Меркурий 230 ART-00 N
![image](https://github.com/Manjey73/OpenDrivers/assets/2898361/10f24ebf-bf66-4a08-9f08-babbd2ffd965)

Меркурий 230 ART-00 PQSIDN
![image](https://github.com/Manjey73/OpenDrivers/assets/2898361/90d304c5-194f-4102-ab6c-04b17c1a8d94)

**Comment by baur** [comment]
Прогон ТЕСТ драйвера:

![image](https://github.com/Manjey73/OpenDrivers/assets/2898361/f47e8962-4b80-4b01-b661-578f945bc594)

![image](https://github.com/Manjey73/OpenDrivers/assets/2898361/3f6c157d-94f8-4523-b00d-0ddc7b766192)

```
2024-06-19 16:13:41 Соединение с IP:26
2024-06-19 16:13:41 Попытка установки TCP-соединения может быть не ранее, чем через 20 с после предыдущей.

2024-06-19 16:13:41 Соединение с IP:26
2024-06-19 16:13:41 Попытка установки TCP-соединения может быть не ранее, чем через 20 с после предыдущей.

2024-06-19 16:13:41 Соединение с IP:26
2024-06-19 16:13:41 Попытка установки TCP-соединения может быть не ранее, чем через 20 с после предыдущей.
```

**Comment by baur** [comment]
Отбой, у нас как раз пинг пропал
но прошу посмотреть остальные параметры

**Comment by baur** [comment]
Log  драйвера TEST_DrvMercury23x_6002.zip 

[line001.log](https://github.com/user-attachments/files/15908195/line001.log)

```
[1] Меркурий
------------
Статус      : норма
Канал связи : TCP-клиент

Общие данные (20)
-----------------
Меркурий236_2 = SN_0 Изготовлен 01.01.0001 Время архива 01.01.0001 0:00:00
Меркурий236_91 = SN_29901891 Изготовлен 19.02.2017 Время архива 01.01.0001 0:00:00
Меркурий236_20 = SN_29901905 Изготовлен 19.02.2017 Время архива 01.01.0001 0:00:00
Меркурий236_10 = SN_29902166 Изготовлен 19.02.2017 Время архива 01.01.0001 0:00:00
Меркурий236_12 = SN_0 Изготовлен 01.01.0001 Время архива 01.01.0001 0:00:00
Меркурий236_25 = SN_0 Изготовлен 01.01.0001 Время архива 01.01.0001 0:00:00
Меркурий236_11 = SN_48411611 Изготовлен 29.05.2023 Время архива 01.01.0001 0:00:00
Меркурий236_14 = SN_0 Изготовлен 01.01.0001 Время архива 01.01.0001 0:00:00
Меркурий236_24 = SN_0 Изготовлен 01.01.0001 Время архива 01.01.0001 0:00:00
Меркурий236_37 = SN_0 Изготовлен 01.01.0001 Время архива 01.01.0001 0:00:00
Меркурий236_8 = SN_26933623 Изготовлен 03.06.2016 Время архива 01.01.0001 0:00:00
Меркурий236_13 = SN_0 Изготовлен 01.01.0001 Время архива 01.01.0001 0:00:00
Меркурий236_5 = SN_0 Изготовлен 01.01.0001 Время архива 01.01.0001 0:00:00
Меркурий236_16 = SN_48411616 Изготовлен 29.05.2023 Время архива 01.01.0001 0:00:00
Меркурий236_4 = SN_0 Изготовлен 01.01.0001 Время архива 01.01.0001 0:00:00
Меркурий236_26 = SN_0 Изготовлен 01.01.0001 Время архива 01.01.0001 0:00:00
Меркурий236_19 = SN_29901926 Изготовлен 19.02.2017 Время архива 01.01.0001 0:00:00
Меркурий236_15 = SN_0 Изготовлен 01.01.0001 Время архива 01.01.0001 0:00:00
Меркурий236_18 = SN_21991912 Изготовлен 02.02.2015 Время архива 20.06.2024 9:30:00
Меркурий236_17 = SN_0 Изготовлен 01.01.0001 Время архива 01.01.0001 0:00:00

Устройства (20)
---------------
[1] РП2 Ввод-1 Яч.#2    : не определён
[2] РП2 Ввод-2 Яч.#19   : не определён
[3] РП4 Ввод-1 Яч.#2    : не определён
[4] РП4 Ввод-1 Яч.#19   : не определён
[5] РП7 Ввод-1 Яч.#1    : не определён
[6] РП7 Ввод-1 Яч.#4    : не определён
[7] РП11 Ввод-1 Яч.#15  : не определён
[8] РП11 Ввод-1 Яч.#26  : не определён
[9] РП12 Ввод-1 Яч.#15  : не определён
[10] РП12 Ввод-1 Яч.#26 : не определён
[11] РП13 Ввод-1 Яч.#15 : не определён
[12] РП13 Ввод-1 Яч.#24 : не определён
[13] РП14 Ввод-1 Яч.#8  : не определён
[14] РП14 Ввод-1 Яч.#1  : норма
[15] РП15 Ввод-1 Яч.#7  : не определён
[16] РП15 Ввод-1 Яч.#2  : не определён
[17] РП1 Ввод-1 Яч.#2   : не определён
[18] РП1 Ввод-2 Яч.#19  : не определён
[19] РП3 Ввод-1 Яч.#2   : не определён
[20] РП3 Ввод-1 Яч.#19  : не определён

```

Есть 3 вида ошибки:

```
2024-06-20 08:39:32 Ошибка при вызове метода Session устройства [4] РП4 Ввод-1 Яч.#19:
System.Collections.Generic.KeyNotFoundException: The given key 'Status' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Scada.Comm.Drivers.DrvMercury23x.Logic.DevMercury23xLogic.Session()
   at Scada.Comm.Engine.DeviceWrapper.Session()
```

```
2024-06-20 08:44:50 Ошибка при вызове метода Session устройства [16] РП15 Ввод-1 Яч.#2:
System.Collections.Generic.KeyNotFoundException: The given key 'Status' was not present in the dictionary.
   at Scada.Comm.Drivers.DrvMercury23x.Logic.DevMercury23xLogic.Session()
   at Scada.Comm.Engine.DeviceWrapper.Session()
```

```
2024-06-20 08:38:37 Ошибка при вызове метода Session устройства [15] РП15 Ввод-1 Яч.#7:
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
   at Scada.Comm.Drivers.DrvMercury23x.Logic.DevMercury23xLogic.Session()
   at Scada.Comm.Engine.DeviceWrapper.Session()
```

Еще 1 момент, время от времени статус от не определён меняется на ошибка и опрос останавливается кроме  Меркурий 230 ART-00 PQSIDN

**Comment by baur** [comment]
Еще 1 момент, время от времени статус от не определён меняется на ошибка и опрос останавливается кроме Меркурий 230 ART-00 PQSIDN

Вот тут ночью опрос остановился, статус выдал ошибка, опрос возобновился только после перезапуска линий  

[line001.log](https://github.com/user-attachments/files/15908337/line001.log) (лог до перезапуска)

![image](https://github.com/Manjey73/OpenDrivers/assets/2898361/d11dc42a-4acc-449a-958e-4b10ef4d5db8)

**Comment by baur** [comment]
[15] РП15 Ввод-1 Яч.#7

![image](https://github.com/Manjey73/OpenDrivers/assets/2898361/51bb9ceb-0885-4ea0-b582-4d217b1e0e9a)

**Comment by baur** [comment]
2024-07-15 13:41:55 Ошибка при вызове метода Session устройства [16] РП15 Ввод-1 Яч.#2:
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at Scada.Comm.Drivers.DrvMercury23x.Logic.DevMercury23xLogic.Session()
   at Scada.Comm.Engine.DeviceWrapper.Session()


Логи перед ошибкой по синхронизации

[line001_1.log](https://github.com/user-attachments/files/16232056/line001_1.log)
[line001_2.log](https://github.com/user-attachments/files/16232041/line001_2.log)

**Comment by kotto78** [comment]
Доброго времени суток.
А вы можете у этого ПУ конфигуратором посмотреть время, не убежал/не отстал ли он сильно? Во всех этих Меркуриях корректировка времени возможна только в пределах 4х минут, о чём в документации на ПУ не очень то написано, а вот в описании конфигуратора есть. Если разница больше, то изменить время  можно только "Установкой времени", но не коррекцией.
Возможно поэтому эта ошибка и возникает.

> 2024-07-15 13:41:55 Ошибка при вызове метода Session устройства [16] РП15 Ввод-1 Яч.#2: System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime...

**Comment by Manjey73** [comment]
По идее, если разница времени больше 4-х минут то коррекция времени должна проходить постепенно в пределах 4-х минут каждые последующие сутки.
Но долго этот момент не тестировал. Попробую выставить время на счетчике с большей разницей и понаблюдать.

**Comment by kotto78** [comment]
> По идее, если разница времени больше 4-х минут то коррекция времени должна проходить постепенно в пределах 4-х минут каждые последующие сутки. Но долго этот момент не тестировал. Попробую выставить время на счетчике с большей разницей и понаблюдать.

По идее да, я тоже так думал. Но вот передо мной лежит ПУ Меркурий 230 который убежав на 21 минуту 32 секунды корректироваться отказывается. Месяц назад делали подстанцию, там тоже несколько корректироваться не стали, пришлось согласовывать и вручную менять время, профили мощности понятное дело несколько пострадали.
А, и все ПУ относительно старые, 2008, 2011, 2013 год. Новых убежавших не пробовал, может они с прошивкой чего-то и улучшили.
